### PR TITLE
feat: allow symfony 7

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Comment by kamilkem** [comment]
Hello @Chris53897, how about releasing this changes?

**Comment by Chris53897** [comment]
This is up to @malukenho
I think close and reopen this PR could be useful to rerun the ci

**Review by malukenho — APPROVED** [review]

**Comment by malukenho** [comment]
These changes look good! I'll take care of the psalm issue.

**Comment by malukenho** [comment]
@kamilkem I've tagged `1.1.0` just now

**Pull request merged**
