### PR TITLE
support Symfony 4

### PR DESCRIPTION
**Pull request by othillo**
Hi, I stumbled upon this project and I wanted to try it on a Symfony 4 project. This PR adds support for Symfony 4.

### CODE REVIEW

**Review by sbacelic — COMMENTED** [review]
Single pipe OR is deprecated but retained for backward compatibility so this could as well be changed as official composer docs use double pipe as logical OR

**Comment by malukenho** [comment]
@othillo thank you for the contribution.

Thank you @sbacelic for the review. I'll fix it on a subsequent PR.

**Comment by sbacelic** [comment]
thanks, btw can you tag next release as Symfony 4.0 is now released?

**Comment by malukenho** [comment]
@sbacelic sorry for the late reply. 
I just tagged the version [0.1.7](https://github.com/malukenho/docheader/releases/tag/0.1.7) 😄

**Pull request merged**
